// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Footer → Footer Name*
 */
export interface FooterDocumentDataFooterNameItem {
  /**
   * Link field in *Footer → Footer Name*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_name[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *Footer → Footer Name*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_name[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *Footer → Footer Navigation*
 */
export interface FooterDocumentDataFooterNavigationItem {
  /**
   * Link field in *Footer → Footer Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Label field in *Footer → Footer Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Footer Name field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_name[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_name: prismic.GroupField<Simplify<FooterDocumentDataFooterNameItem>>;

  /**
   * Footer Navigation field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_navigation: prismic.GroupField<
    Simplify<FooterDocumentDataFooterNavigationItem>
  >;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | CardGridSwiperSlice
  | CardImageSlice
  | MainDescriptionSlice
  | HeroBannerSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type ProductDocumentDataSlicesSlice = SingleProductSlice;

/**
 * Content for Product documents
 */
interface ProductDocumentData {
  /**
   * Title field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Price field in *Product*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: product.price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price: prismic.NumberField;

  /**
   * Slice Zone field in *Product*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: product.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProductDocumentDataSlicesSlice> /**
   * Meta Title field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductDocumentData>,
    "product",
    Lang
  >;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | FooterDocument
  | PageDocument
  | ProductDocument
  | SettingsDocument;

/**
 * Item in *CardGridSmall → Default → Primary → Card 1*
 */
export interface CardGridSwiperSliceDefaultPrimaryCard1Item {
  /**
   * Link field in *CardGridSmall → Default → Primary → Card 1*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid_swiper.default.primary.card_1[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Image field in *CardGridSmall → Default → Primary → Card 1*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid_swiper.default.primary.card_1[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *CardGridSmall → Default → Primary → Card 1*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid_swiper.default.primary.card_1[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Price field in *CardGridSmall → Default → Primary → Card 1*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid_swiper.default.primary.card_1[].price
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price: prismic.NumberField;
}

/**
 * Item in *CardGridSmall → Default → Primary → Card 2*
 */
export interface CardGridSwiperSliceDefaultPrimaryCard2Item {
  /**
   * Link field in *CardGridSmall → Default → Primary → Card 2*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid_swiper.default.primary.card_2[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Image field in *CardGridSmall → Default → Primary → Card 2*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid_swiper.default.primary.card_2[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *CardGridSmall → Default → Primary → Card 2*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid_swiper.default.primary.card_2[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Price field in *CardGridSmall → Default → Primary → Card 2*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid_swiper.default.primary.card_2[].price
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price: prismic.NumberField;
}

/**
 * Item in *CardGridSmall → Default → Primary → Card 3*
 */
export interface CardGridSwiperSliceDefaultPrimaryCard3Item {
  /**
   * Link field in *CardGridSmall → Default → Primary → Card 3*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid_swiper.default.primary.card_3[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Image field in *CardGridSmall → Default → Primary → Card 3*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid_swiper.default.primary.card_3[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *CardGridSmall → Default → Primary → Card 3*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid_swiper.default.primary.card_3[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Price field in *CardGridSmall → Default → Primary → Card 3*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid_swiper.default.primary.card_3[].price
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price: prismic.NumberField;
}

/**
 * Item in *CardGridSmall → Default → Primary → Button Link*
 */
export interface CardGridSwiperSliceDefaultPrimaryButtonLinkItem {
  /**
   * Link field in *CardGridSmall → Default → Primary → Button Link*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid_swiper.default.primary.button_link[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Title field in *CardGridSmall → Default → Primary → Button Link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid_swiper.default.primary.button_link[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *CardGridSmall → Default → Primary*
 */
export interface CardGridSwiperSliceDefaultPrimary {
  /**
   * Card 1 field in *CardGridSmall → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid_swiper.default.primary.card_1[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  card_1: prismic.GroupField<
    Simplify<CardGridSwiperSliceDefaultPrimaryCard1Item>
  >;

  /**
   * Card 2 field in *CardGridSmall → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid_swiper.default.primary.card_2[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  card_2: prismic.GroupField<
    Simplify<CardGridSwiperSliceDefaultPrimaryCard2Item>
  >;

  /**
   * Card 3 field in *CardGridSmall → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid_swiper.default.primary.card_3[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  card_3: prismic.GroupField<
    Simplify<CardGridSwiperSliceDefaultPrimaryCard3Item>
  >;

  /**
   * Button Link field in *CardGridSmall → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: card_grid_swiper.default.primary.button_link[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  button_link: prismic.GroupField<
    Simplify<CardGridSwiperSliceDefaultPrimaryButtonLinkItem>
  >;
}

/**
 * Default variation for CardGridSmall Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardGridSwiperSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardGridSwiperSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CardGridSmall*
 */
type CardGridSwiperSliceVariation = CardGridSwiperSliceDefault;

/**
 * CardGridSmall Shared Slice
 *
 * - **API ID**: `card_grid_swiper`
 * - **Description**: CardGridSwiper
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardGridSwiperSlice = prismic.SharedSlice<
  "card_grid_swiper",
  CardGridSwiperSliceVariation
>;

/**
 * Item in *CardGridBig → Default → Primary → Card*
 */
export interface CardImageSliceDefaultPrimaryCardItem {
  /**
   * Product Properties field in *CardGridBig → Default → Primary → Card*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: card_image.default.primary.card[].product_properties
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  product_properties: prismic.ContentRelationshipField<"product_properties">;
}

/**
 * Primary content in *CardGridBig → Default → Primary*
 */
export interface CardImageSliceDefaultPrimary {
  /**
   * Card field in *CardGridBig → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: card_image.default.primary.card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  card: prismic.GroupField<Simplify<CardImageSliceDefaultPrimaryCardItem>>;
}

/**
 * Default variation for CardGridBig Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CardGridBig*
 */
type CardImageSliceVariation = CardImageSliceDefault;

/**
 * CardGridBig Shared Slice
 *
 * - **API ID**: `card_image`
 * - **Description**: CardImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardImageSlice = prismic.SharedSlice<
  "card_image",
  CardImageSliceVariation
>;

/**
 * Primary content in *HeroBanner → Default → Primary*
 */
export interface HeroBannerSliceDefaultPrimary {
  /**
   * Hero Image field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.default.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;
}

/**
 * Default variation for HeroBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroBanner*
 */
type HeroBannerSliceVariation = HeroBannerSliceDefault;

/**
 * HeroBanner Shared Slice
 *
 * - **API ID**: `hero_banner`
 * - **Description**: HeroBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerSlice = prismic.SharedSlice<
  "hero_banner",
  HeroBannerSliceVariation
>;

/**
 * Primary content in *MainDescription → Default → Primary*
 */
export interface MainDescriptionSliceDefaultPrimary {
  /**
   * Title field in *MainDescription → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main_description.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *MainDescription → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main_description.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for MainDescription Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainDescriptionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MainDescriptionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MainDescription*
 */
type MainDescriptionSliceVariation = MainDescriptionSliceDefault;

/**
 * MainDescription Shared Slice
 *
 * - **API ID**: `main_description`
 * - **Description**: MainDescription
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainDescriptionSlice = prismic.SharedSlice<
  "main_description",
  MainDescriptionSliceVariation
>;

/**
 * Primary content in *SingleProduct → Default → Primary*
 */
export interface SingleProductSliceDefaultPrimary {
  /**
   * Product field in *SingleProduct → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: single_product.default.primary.product
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  product: prismic.ContentRelationshipField<"product_properties">;
}

/**
 * Default variation for SingleProduct Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SingleProductSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SingleProductSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SingleProduct*
 */
type SingleProductSliceVariation = SingleProductSliceDefault;

/**
 * SingleProduct Shared Slice
 *
 * - **API ID**: `single_product`
 * - **Description**: SingleProduct
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SingleProductSlice = prismic.SharedSlice<
  "single_product",
  SingleProductSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataFooterNameItem,
      FooterDocumentDataFooterNavigationItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProductDocument,
      ProductDocumentData,
      ProductDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      CardGridSwiperSlice,
      CardGridSwiperSliceDefaultPrimaryCard1Item,
      CardGridSwiperSliceDefaultPrimaryCard2Item,
      CardGridSwiperSliceDefaultPrimaryCard3Item,
      CardGridSwiperSliceDefaultPrimaryButtonLinkItem,
      CardGridSwiperSliceDefaultPrimary,
      CardGridSwiperSliceVariation,
      CardGridSwiperSliceDefault,
      CardImageSlice,
      CardImageSliceDefaultPrimaryCardItem,
      CardImageSliceDefaultPrimary,
      CardImageSliceVariation,
      CardImageSliceDefault,
      HeroBannerSlice,
      HeroBannerSliceDefaultPrimary,
      HeroBannerSliceVariation,
      HeroBannerSliceDefault,
      MainDescriptionSlice,
      MainDescriptionSliceDefaultPrimary,
      MainDescriptionSliceVariation,
      MainDescriptionSliceDefault,
      SingleProductSlice,
      SingleProductSliceDefaultPrimary,
      SingleProductSliceVariation,
      SingleProductSliceDefault,
    };
  }
}
