// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  card_image: defineAsyncComponent(() => import("./CardGridBig/index.vue")),
  hero_banner: defineAsyncComponent(() => import("./HeroBanner/index.vue")),
  main_description: defineAsyncComponent(
    () => import("./MainDescription/index.vue"),
  ),
  single_product: defineAsyncComponent(
    () => import("./SingleProduct/index.vue"),
  ),
});
